version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: kkcg_analytics
      POSTGRES_USER: kkcg_user
      POSTGRES_PASSWORD: kkcg_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kkcg_network

  # FastAPI Backend
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://kkcg_user:kkcg_password@postgres:5432/kkcg_analytics
      SECRET_KEY: your-super-secret-development-key-here
      DEBUG: "True"
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - kkcg_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # pgAdmin (optional - for database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kkcg.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - kkcg_network

volumes:
  postgres_data:

networks:
  kkcg_network:
    driver: bridge 