[theme]
base = "dark"
primaryColor = "#FF6B35"
backgroundColor = "#1a1a2e"
secondaryBackgroundColor = "#2a2a3e"
textColor = "#E8F4FD"
font = "sans serif"

[server]
headless = true
port = 8501
maxUploadSize = 200
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
showErrorDetails = false

[client]
showErrorDetails = false

# Performance optimizations to reduce warnings
[global]
developmentMode = false
showWarningOnDirectExecution = false 